# Generated by Django 5.0.2 on 2024-02-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico_mesada',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mesada',
            old_name='valor',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='mesada',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historico_mesada',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesada',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.userprofileinfo'),
            preserve_default=False,
        ),
    ]
