# Generated by Django 5.0.2 on 2024-02-17 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_usuario_historico_mesada_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesada',
            old_name='total',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='historico_mesada',
            name='total',
        ),
        migrations.RemoveField(
            model_name='mesada',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='mesada',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
