# Generated by Django 5.0.2 on 2024-02-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_total_mesada_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesada',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
