# Generated by Django 5.0.2 on 2024-02-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofileinfo_valor_mesada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico_mesada',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mesada',
            old_name='usuario',
            new_name='user',
        ),
    ]
