version: '3'

services:
  web:
    image: python:3.8
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - ./db:/db
