# Generated by Django 5.0.2 on 2024-02-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_mesada_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesada',
            name='user',
        ),
        migrations.AddField(
            model_name='mesada',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.userprofileinfo'),
            preserve_default=False,
        ),
    ]
