# Generated by Django 5.0.2 on 2024-02-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historico_mesada_total_mesada_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesada',
            name='valor',
        ),
    ]
