# Generated by Django 5.0.2 on 2024-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofileinfo_valor_mesada'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='valor_mesada',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
